"""add soft delete to files

Revision ID: 1861beddd458
Revises: 7044dbdcd1eb
Create Date: 2026-07-25 22:39:21.368657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1861beddd458'
down_revision: Union[str, Sequence[str], None] = '7044dbdcd1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_deleted', sa.Boolean(), nullable=False,server_default=sa.false()))
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.alter_column(
        'files',
        "is_deleted",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'deleted_at')
    op.drop_column('files', 'is_deleted')
    # ### end Alembic commands ###
