"""create audit_logs and shared_files table

Revision ID: 43376d4a6a9f
Revises: 4f1891f75313
Create Date: 2026-07-27 15:49:46.473808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43376d4a6a9f'
down_revision: Union[str, Sequence[str], None] = '4f1891f75313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_file_id'), 'audit_logs', ['file_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_folder_id'), 'audit_logs', ['folder_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('shared_files',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
    "ix_audit_logs_created_at",
    "audit_logs",
    ["created_at"],
    )
    op.create_index(op.f('ix_shared_files_created_by'), 'shared_files', ['created_by'], unique=False)
    op.create_index(op.f('ix_shared_files_file_id'), 'shared_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_shared_files_token'), 'shared_files', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_files_token'), table_name='shared_files')
    op.drop_index(op.f('ix_shared_files_file_id'), table_name='shared_files')
    op.drop_index(op.f('ix_shared_files_created_by'), table_name='shared_files')
    op.drop_table('shared_files')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_folder_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_file_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
