"""add storage quota to users

Revision ID: 4f1891f75313
Revises: 1861beddd458
Create Date: 2026-07-26 15:39:54.730824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.constants import FREE_STORAGE_LIMIT


# revision identifiers, used by Alembic.
revision: str = '4f1891f75313'
down_revision: Union[str, Sequence[str], None] = '1861beddd458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_used', sa.BigInteger(), nullable=False,server_default="0"))
    op.add_column('users', sa.Column('storage_limit', sa.BigInteger(), nullable=False,server_default=str(FREE_STORAGE_LIMIT)))
    # ### end Alembic commands ###
    op.alter_column(
        "users",
        "storage_used",
        server_default=None,
    )

    op.alter_column(
        "users",
        "storage_limit",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_limit')
    op.drop_column('users', 'storage_used')
    # ### end Alembic commands ###
