"""add storage path to files

Revision ID: 7044dbdcd1eb
Revises: 137ffd66cb1d
Create Date: 2026-07-25 01:17:01.454956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7044dbdcd1eb'
down_revision: Union[str, Sequence[str], None] = '137ffd66cb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('storage_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'storage_path')
    # ### end Alembic commands ###
