"""create the permission table

Revision ID: dba74ac90149
Revises: 43376d4a6a9f
Create Date: 2026-07-31 21:49:05.052471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba74ac90149'
down_revision: Union[str, Sequence[str], None] = '43376d4a6a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('FILE', 'FOLDER', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'EDITOR', name='permissionrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_type', 'resource_id', name='uq_permission_per_resource')
    )
    op.create_index('ix_permission_resource', 'permissions', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_permissions_resource_id'), 'permissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_permissions_user_id'), 'permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_permissions_user_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_resource_id'), table_name='permissions')
    op.drop_index('ix_permission_resource', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
